[package]
name = "fs-scan"
version = "0.3.2"
authors = ["alexandre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"
indicatif = "0.14.0"